Repository prgrms-web-devcourse/Team-BackFro-ArtZip-FE, pull requests merged in 2022-08, with the labels that each got.

#47 feat: ReviewCard 구현
  .husky/pre-commit
  components/molecule/ReviewCard/index.tsx
  components/molecule/ReviewCard/style.ts
  components/molecule/index.ts
  pages/exhibitions/detail/[id]/index.tsx
  pages/index.tsx
Labels: 우선순위: 보통

#56 feat: api interface 정의
  components/molecule/ExhibitionCard/index.tsx
  types/apis/base.ts
  types/apis/comment/index.ts
  types/apis/exhibition/index.ts
  types/apis/user/index.ts
  types/model.ts
Labels: 우선순위: 급함

#58 feat: 감상평 컴포넌트 구현
  .husky/pre-commit
  .vscode
  components/atom/LikeToggle/index.tsx
  components/atom/LinkButton/index.tsx
  components/atom/index.ts
  components/molecule/ImageGroup/index.tsx
  components/molecule/LikeInfo/index.tsx
  components/molecule/UserInfo/index.tsx
  components/molecule/index.ts
  components/organism/InfoGroup/index.tsx
  components/organism/ReviewDetail/index.tsx
  components/organism/ReviewFeed/index.tsx
  components/organism/index.ts
  mocks/handlers/comment/index.ts
  mocks/handlers/review/index.ts
  pages/_app.tsx
  pages/reviews/detail/[id]/index.tsx
  styles/theme/emotion.d.ts
  styles/theme/index.ts
  types/apis/review/index.ts
  types/model.ts
Labels: 리뷰 요청, 우선순위: 보통

#84 feat: 전시회 상세 페이지 마크업
  components/molecule/ReviewCard/index.tsx
  components/molecule/ReviewCard/style.ts
  mocks/handlers.ts
  mocks/handlers/exhibition/index.ts
  pages/exhibitions/detail/[id]/index.tsx
  pages/exhibitions/detail/[id]/style.ts
Labels: 리뷰 요청, 우선순위: 보통

#83 feat: 맞춤전시회 toolbar 구현
  components/molecule/CommentInfo/index.tsx
  components/organism/SearchToolbar/index.tsx
  components/organism/SearchToolbar/style.ts
  constants/exhibitionPeriod.ts
  constants/exhibitionPlace.ts
  constants/index.ts
  constants/styles/theme.ts
  pages/index.tsx
  pages/search-result/index.tsx
Labels: 리뷰 요청

#98 feat: 라우터 수정
  components/organism/Header/index.tsx
  components/organism/SwiperContainer/index.tsx
  pages/exhibitions/custom/index.tsx
  pages/exhibitions/more/index.tsx
  pages/index.tsx
Labels: 우선순위: 급함

#92 feat: 로그인 페이지 마크업
  pages/signin/index.tsx
Labels: 리뷰 요청, 우선순위: 보통

#85 feat: ScrollButton 컴포넌트 구현
  components/molecule/ScrollButton/index.tsx
  components/molecule/index.ts
Labels: 리뷰 요청, 우선순위: 보통

#91 feat: ReviewExhibitionInfo 컴포넌트 구현
  components/molecule/ReviewExhibitionInfo/index.tsx
  components/molecule/index.ts
  components/organism/ReviewDetail/index.tsx
Labels: 리뷰 요청, 우선순위: 보통

#111 refactor: Pagination에 대한 interface 분리
  types/apis/base.ts
  types/apis/comment/index.ts
  types/apis/exhibition/index.ts
  types/model.ts
Labels: 리뷰 요청

#117 fix: api 명세 수정에 따른 타입 수정
  components/organism/ReviewDetail/index.tsx
  mocks/handlers/comment/index.ts
  mocks/handlers/review/index.ts
  pages/reviews/detail/[id]/index.tsx
  types/apis/review/index.ts
Labels: 우선순위: 급함

#113 feat: axios 초기 설정 및 API 추가
  apis/comment/index.ts
  apis/common.ts
  apis/exhibition/index.ts
  apis/index.ts
  apis/review/index.ts
  apis/user/index.ts
  hooks/useAxios/index.ts
  hooks/useAxios/useAxiosFn.ts
  types/apis/comment/index.ts
  types/apis/user/index.ts
  utils/index.ts
  utils/storage/index.ts
Labels: 우선순위: 급함

#130 fix: API 명세 변경에 따른 타입 수정
  components/molecule/ExhibitionCard/index.tsx
  components/organism/ReviewDetail/index.tsx
  mocks/handlers/review/index.ts
  pages/community/index.tsx
  pages/reviews/detail/[id]/index.tsx
  types/apis/review/index.ts
  types/model.ts
Labels: 리뷰 요청, 우선순위: 급함

#123 feat: 맞춤페이지 마크업
  components/organism/SearchToolbar/style.ts
  pages/exhibitions/custom/index.tsx
  pages/exhibitions/more/index.tsx
  pages/index.tsx
  pages/search-result/index.tsx
  styles/pages/exhibitionsCustom.ts
Labels: 리뷰 요청

#122 feat: 댓글 컴포넌트 구현
  components/atom/NotLoginAvatar/index.tsx
  components/atom/UserAvatar/index.tsx
  components/atom/index.ts
  components/molecule/UserInfo/index.tsx
  components/organism/CommentList/index.tsx
  components/organism/CommentUtils/index.tsx
  components/organism/CommentWrite/index.tsx
  components/organism/ReviewDetail/index.tsx
  components/organism/index.ts
  hooks/index.ts
  hooks/useClickAway/index.ts
  mocks/handlers.ts
  mocks/handlers/comment/index.ts
  pages/reviews/detail/[id]/index.tsx
  styles/global/globals.css
  types/model.ts
Labels: 리뷰 요청

#136 refactor: authRequest의 토큰 전달 수정
  apis/common.ts
Labels: 우선순위: 급함

#134 feat: Map 컴포넌트 구현
  .env.development
  .env.production
  .gitignore
  components/atoms/Map/index.tsx
  components/atoms/Map/style.ts
  pages/_app.tsx
  pages/index.tsx
  styles/pages/homeStyle.ts
  styles/pages/index.ts
Labels: 리뷰 요청

#143 feat: 메인페이지 서버통신 구현
  components/molecule/ExhibitionCard/index.tsx
  components/organism/Swiper/index.tsx
  next.config.js
  pages/index.tsx
Labels: 우선순위: 급함

#155 feat: 로그인 로직 수정
  .env.development
  apis/common.ts
  apis/refresh/index.ts
  apis/user/index.ts
  hooks/useUserAuthActions/index.ts
  package.json
  pages/_app.tsx
  pages/signup/index.tsx
  states/user.ts
  utils/cookie/index.ts
  utils/index.ts
  utils/parseJwt/index.ts
  utils/tokenManager/index.ts
  yarn.lock
Labels: 우선순위: 급함

#157 feat: 유저페이지 API 연동하여 기능 구현
  apis/user/index.ts
  components/atoms/LinkText/index.tsx
  components/molecule/ReviewCard/index.tsx
  components/molecule/SideNavigation/index.tsx
  components/organism/Header/index.tsx
  constants/imageUrl.ts
  pages/users/[id]/edit-password/index.tsx
  pages/users/[id]/edit/index.tsx
  pages/users/[id]/index.tsx
  types/apis/user/index.ts
  types/model.ts
Labels: 우선순위: 급함

#166 feat: 로그아웃 구현
  apis/user/index.ts
  components/molecule/SideNavigation/index.tsx
  components/organism/Header/index.tsx
  hooks/useUserAuthActions/index.ts
  pages/users/[id]/edit-password/index.tsx
  pages/users/[id]/edit/index.tsx
Labels: 우선순위: 급함

#147 feat: 더보기페이지 서버통신 구현
  pages/exhibitions/more/index.tsx
Labels: 리뷰 요청

#167 feat: 후기 관련 페이지 API 로직 구현
  apis/review/index.ts
  components/organism/ReviewDetail/index.tsx
  components/organism/ReviewFeed/index.tsx
  pages/_app.tsx
  pages/community/index.tsx
  pages/reviews/detail/[id]/index.tsx
  states/user.ts
  types/model.ts
Labels: 리뷰 요청, 우선순위: 급함

#182 feat: 댓글 관련 기능 구현
  apis/comment/index.ts
  apis/common.ts
  apis/review/index.ts
  components/organism/CommentList/index.tsx
  components/organism/CommentUtils/index.tsx
  components/organism/CommentWrite/index.tsx
  components/organism/Header/index.tsx
  components/organism/ReplyUtils/index.tsx
  components/organism/index.ts
  constants/index.ts
  constants/userLoginState.ts
  hooks/useUserAuthActions/index.ts
  pages/_app.tsx
  pages/community/index.tsx
  pages/reviews/detail/[id]/index.tsx
  states/user.ts
  types/model.ts
Labels: 리뷰 요청, 우선순위: 급함

#179 feat: 리뷰 컨테이너 수정
  components/molecule/ReviewCard/index.tsx
  hooks/useUserAuthActions/index.ts
  pages/exhibitions/detail/[id]/index.tsx
  styles/pages/exhibitionsStyle.ts
  types/apis/exhibition/index.ts
Labels: 리뷰 요청, 우선순위: 급함

#183 feat: 검색결과 서버통신 구현
  pages/exhibitions/more/index.tsx
  pages/search-result/index.tsx
Labels: 리뷰 요청

#195 design: reviewFeed 줄바꿈 속성 추가
  components/organism/ReviewFeed/style.ts
Labels: 우선순위: 급함

#204 fix: _app 에서 접근하지 못하는 코드 삭제
  pages/_app.tsx
  utils/tokenManager/index.ts
Labels: 🔥 핫픽스

#226 fix: 검색 여러번 안 되는 버그 수정
  components/organisms/Header/index.tsx
  pages/search-result/[exhibition]/index.tsx
Labels: 리뷰 요청

#238 refactor: 유저페이지의 SSR을 CSR로 변경
  apis/user/index.ts
  pages/_app.tsx
  pages/users/[id]/index.tsx
Labels: 리뷰 요청

#237 feat: 소셜로그인 버튼 변경 및 레이아웃 수정
  pages/signin/index.tsx
  public/kakao_login_medium_wide.png
Labels: 리뷰 요청
