Repository prgrms-web-devcourse/Team-BackFro-ArtZip-FE, pull requests merged in 2022-10, with the labels that each got.

#251 fix: 스와이퍼 같이 움직이는 오류 수정
  components/organisms/Swiper/index.tsx
  components/organisms/Swiper/style.ts
  pages/index.tsx
Labels: 리뷰 요청

#302 refactor: SWR 캐시로 인한 깜빡임 현상 수정
  components/organisms/ReviewDetail/index.tsx
  components/organisms/ReviewFeed/index.tsx
  pages/community/index.tsx
  pages/reviews/update/[id]/index.tsx
  utils/swrOptions/index.ts
Labels: 리팩터링

#301 hotfix: 서버사이드 인증 관련 문제 해결
  apis/comment/index.ts
  apis/common.ts
  apis/exhibition/index.ts
  apis/review/index.ts
  apis/user/index.ts
  components/molecules/ExhibitionCard/index.tsx
  components/organisms/CommentWrite/index.tsx
  hooks/useUserAuthActions/index.ts
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/users/[id]/edit/index.tsx
  states/user.ts
  utils/index.ts
  utils/swrOptions/index.ts
  utils/tokenManager/index.ts
  yarn.lock
Labels: 우선순위: 급함, 🔥 핫픽스, 리팩터링

#319 feat: ReviewEditForm 모듈화 & 자동 저장 구현
  components/organisms/ExhibitionSearchBar/index.tsx
  components/organisms/ReviewEditForm/index.tsx
  components/organisms/index.ts
  hooks/index.ts
  hooks/useDraftReview/index.ts
  hooks/useInput/index.ts
  hooks/useSessionStorage/index.ts
  pages/exhibitions/detail/[id]/index.tsx
  pages/reviews/create/index.tsx
  pages/reviews/update/[id]/index.tsx
  utils/validation/index.ts
Labels: 리뷰 요청

#328 refactor: 토큰 관련 로직 모듈화 및 상수 분리
  apis/comment/index.ts
  apis/common.ts
  apis/exhibition/index.ts
  apis/review/index.ts
  apis/user/index.ts
  constants/index.ts
  constants/tokenKey.ts
  hooks/useUserAuthActions/index.ts
  pages/_app.tsx
  pages/index.tsx
  pages/oauth/callback/index.tsx
  states/user.ts
  utils/index.ts
  utils/swrOptions/index.ts
  utils/tokenManager/index.ts
Labels: 리뷰 요청, 리팩터링

#334 refactor: ReviewEditForm 렌더링 성능 개선
  components/organisms/ExhibitionSearchBar/index.tsx
  components/organisms/ImageUpload/index.tsx
  components/organisms/ReviewEditForm/fields/ContentTextArea/index.tsx
  components/organisms/ReviewEditForm/fields/DateInput/index.tsx
  components/organisms/ReviewEditForm/fields/ExhibitionSearchBar/index.tsx
  components/organisms/ReviewEditForm/fields/ImageUpload/PrevImageList/index.tsx
  components/organisms/ReviewEditForm/fields/ImageUpload/index.tsx
  components/organisms/ReviewEditForm/fields/IsPublicSwitch/index.tsx
  components/organisms/ReviewEditForm/fields/TitleInput/index.tsx
  components/organisms/ReviewEditForm/fields/index.ts
  components/organisms/ReviewEditForm/index.tsx
  components/organisms/ReviewEditForm/utils/ErrorMessage/index.tsx
  components/organisms/ReviewEditForm/utils/constants/index.ts
  components/organisms/index.ts
  hooks/index.ts
  hooks/useDraftReview/index.ts
  hooks/useSessionStorage/index.ts
  hooks/useStoredReview/index.ts
  pages/_document.tsx
  pages/reviews/create/index.tsx
  pages/reviews/update/[id]/index.tsx
  utils/index.ts
  utils/validation/index.ts
Labels: 최적화, 리팩터링

#335 chore: 테스팅 도입 및 환경 설정
  components/organisms/ExhibitionSearchBar/index.test.tsx
  components/organisms/ReviewEditForm/index.test.tsx
  jest.config.js
  jest.setup.js
  package.json
  yarn.lock
Labels: 리뷰 요청

#331 feat: 페이지 전환 시 로딩 컴포넌트 추가
  components/molecules/Loading/index.tsx
  components/molecules/index.ts
  pages/_app.tsx
Labels: 리팩터링

#337 refactor: 전시회 상세 페이지 SSR 적용
  components/organisms/ExhibitionDetail/index.tsx
  components/organisms/ExhibitionDetail/style.ts
  pages/exhibitions/detail/[id]/index.tsx
Labels: 리뷰 요청, 리팩터링

#343 refactor: ReviewEditForm 코드 개선
  components/organisms/ReviewEditForm/fields/ExhibitionSearchBar/index.tsx
  components/organisms/ReviewEditForm/index.tsx
  pages/reviews/create/index.tsx
Labels: 리팩터링

#342 design: ExhibitionCard 에서 호버 시 text 가 제일 위로 올라오도록 수정
  components/molecules/ExhibitionCard/index.tsx
  components/molecules/ExhibitionCard/style.ts
  pages/index.tsx
Labels: 리뷰 요청, 리팩터링
