Repository prgrms-web-devcourse/Team-BackFro-ArtZip-FE, pull requests merged in 2022-09, with the labels that each got.

#250 feat: 메인페이지 getServersideProps 도입
  pages/index.tsx
Labels: 리뷰 요청

#258 design: 리뷰 디테일 페이지 반응형 작업
  components/molecules/ReviewExhibitionInfo/index.tsx
  components/molecules/ReviewExhibitionInfo/style.ts
  components/organisms/CommentList/index.tsx
  components/organisms/CommentUtils/index.tsx
  components/organisms/CommentWrite/index.tsx
  components/organisms/ReviewDetail/index.tsx
  components/organisms/ReviewDetail/style.ts
  hooks/useUserAuthActions/index.ts
  pages/reviews/detail/[id]/index.tsx
  types/apis/user/index.ts
  types/model.ts
Labels: 리뷰 요청

#249 fix: 헤더 검색 완료 시, value가 남아있는 버그 수정
  components/organisms/Header/index.tsx
  pages/search-result/[exhibition]/index.tsx
Labels: 리뷰 요청

#257 feat: useDebounceClick 커스텀 훅 구현
  hooks/index.ts
  hooks/useDebounce/click.ts
  pages/reviews/create/index.tsx
  pages/reviews/update/[id]/index.tsx
  pages/users/[id]/edit-password/index.tsx
  pages/users/[id]/edit/index.tsx
Labels: 리뷰 요청

#252 feat: 리뷰 디테일 페이지 csr로직 swr로 변경
  pages/reviews/detail/[id]/index.tsx
Labels: 리뷰 요청, 리팩터링

#248 feat: 커뮤니티 페이지 CSR 로직 SWR 으로 변경
  pages/_app.tsx
  pages/community/index.tsx
  utils/index.ts
  utils/swrOptions/index.ts
Labels: 리뷰 요청

#269 design: 리뷰 디테일 줄바꿈 반영
  components/organisms/ReviewDetail/style.ts
Labels: 리뷰 요청

#265 hotfix: 유저 profileImage 기본 이미지 추가
  components/atoms/UserAvatar/index.tsx
  components/molecules/ReviewCard/index.tsx
  components/organisms/Header/index.tsx
  constants/defaultImage.ts
  constants/index.ts
  pages/reviews/create/index.tsx
  pages/users/[id]/edit/index.tsx
  pages/users/[id]/index.tsx
Labels: 리뷰 요청

#266 fix: 좋아요 버그 수정
  components/organisms/ExhibitionDetail/index.tsx
  pages/exhibitions/detail/[id]/index.tsx
  types/apis/exhibition/index.ts
Labels: 리뷰 요청

#274 design: 커뮤니티 페이지 반응형 구현
  components/organisms/ReviewFeed/index.tsx
  components/organisms/ReviewFeed/style.ts
Labels: 리뷰 요청, 리팩터링

#280 refactor: 클립보드 복사 message추가 및 전시회 상세 피드백 반영
  components/molecules/ExhibitionInfo/index.tsx
  components/organisms/ExhibitionDetail/style.ts
  pages/exhibitions/detail/[id]/index.tsx
  styles/pages/exhibitionsStyle.ts
Labels: 리팩터링

#283 fix: 커뮤니티 페이지와 리뷰 상세 페이지의 좋아요 버그 수정
  components/organisms/ReviewDetail/index.tsx
  components/organisms/ReviewFeed/index.tsx
Labels: 리뷰 요청, 리팩터링

#285 refactor: 후기 작성 페이지 컴포넌트 분리 및 SWR 적용
  components/organisms/ExhibitionSearchBar/index.tsx
  components/organisms/ReviewDetail/index.tsx
  components/organisms/ReviewDetail/style.ts
  components/organisms/index.ts
  pages/reviews/create/index.tsx
  pages/reviews/update/[id]/index.tsx
  utils/validation/index.ts
Labels: 리뷰 요청, 리팩터링

#289 refactor: 로그인 & 회원가입 버튼 중복 클릭 방어
  hooks/useUserAuthActions/index.ts
  pages/signin/index.tsx
  pages/signup/index.tsx
Labels: 최적화, 리팩터링

#298 refactor: ExhibitionCard와 ReviewCard의 props 수정
  components/molecules/ExhibitionCard/index.tsx
  components/molecules/ReviewCard/index.tsx
  components/organisms/Swiper/index.tsx
  pages/exhibitions/custom/index.tsx
  pages/exhibitions/detail/[id]/index.tsx
  pages/exhibitions/more/index.tsx
  pages/index.tsx
  pages/search-result/[exhibition]/index.tsx
  pages/users/[id]/index.tsx
  types/model.ts
Labels: 리팩터링

#296 hotfix: 유저 페이지 무한 로딩 버그 수정
  components/atoms/Spinner/index.tsx
  pages/users/[id]/index.tsx
Labels: 🔥 핫픽스, 리팩터링

#300 refactor: 유저페이지의 컴포넌트 추출 및 SWR 적용
  components/molecules/SideNavigation/index.tsx
  components/molecules/UserProfileCard/index.tsx
  components/molecules/index.ts
  components/organisms/UserActivityCardList/index.tsx
  components/organisms/index.ts
  pages/users/[id]/index.tsx
  types/apis/user/index.ts
Labels: 리팩터링
